import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Lista manual (em vez de autogenerated): cada seção é uma pasta com um
// único arquivo dentro, então autogenerated criava uma categoria
// expansível para cada uma em vez de um link direto. Isso mantém a
// sidebar plana. Adicionar um segundo doc a uma seção não quebra isso —
// só não aparece sozinho até ser incluído aqui.
const sidebars: SidebarsConfig = {
  proposalSidebar: [
    'proposta-e-escopo/visao-geral/index',
    'proposta-e-escopo/arquitetura-tecnica/index',
    'proposta-e-escopo/stack-e-decisoes-tecnicas/index',
    'proposta-e-escopo/plano-e-cronograma/index',
    'proposta-e-escopo/escopo/index',
    'proposta-e-escopo/riscos-e-contingencia/index',
    'proposta-e-escopo/estimativa-custo-horas/index',
    'proposta-e-escopo/design-e-ergonomia/index',
  ],
  desenvolvimentoSidebar: [{type: 'autogenerated', dirName: 'desenvolvimento'}],
};

export default sidebars;
