import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Lista manual (em vez de autogenerated): cada seção é uma pasta com um
// único arquivo dentro, então autogenerated criava uma categoria
// expansível para cada uma em vez de um link direto. Isso mantém a
// sidebar plana. Adicionar um segundo doc a uma seção não quebra isso —
// só não aparece sozinho até ser incluído aqui.
const sidebars: SidebarsConfig = {
  proposalSidebar: [
    'visao-geral/index',
    'arquitetura-tecnica/index',
    'stack-e-decisoes-tecnicas/index',
    'plano-e-cronograma/index',
    'escopo/index',
    'riscos-e-contingencia/index',
    'estimativa-custo-horas/index',
  ],
};

export default sidebars;
