import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Sidebar gerada automaticamente a partir da estrutura de pastas em docs/,
// respeitando a ordem numérica dos prefixos (01-, 02-, ...) e os
// _category_.json de cada seção.
const sidebars: SidebarsConfig = {
  proposalSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
